name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create .kube directory
      run: mkdir -p $HOME/.kube
    - name: Set up Kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
    - name: Sync with Argo CD
      run: |
        kubectl apply -f k8s/
        argocd app sync hello-world
